document.cookie = 'user=Hemant; expires=' + new Date(2021, 9, 20)
sessionStorage.setItem('user', 'Hemant')
sessionStorage.getItem('user')
sessionStorage.removeItem('user')
sessionStorage.clear()
localStorage.setItem('user', 'Hemant')
localStorage.getItem('user')
localStorage.removeItem('user')
localStorage.clear()
